version: 2
jobs:
  test_python:
    working_directory: ~/tiny-cms-project
    docker:
      - image: circleci/python:3.6.2
        environment:
          - DB_USER=root
          - DB_NAME=tiny_project
      - image: circleci/postgres:9.5.10
        environment:
          - POSTGRES_USER=root
          - POSTGRES_DB=tiny_project
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: install python dependencies
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install -U setuptools
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - .venv
      - run:
          name: pylint
          command: |
            . .venv/bin/activate
            pylint tiny_project
      - run:
          name: iSort
          command: |
            . .venv/bin/activate
            isort --check-only tiny_project
      - run:
          name: tests
          command: |
            . .venv/bin/activate
            python manage.py test
workflows:
  version: 2
  test:
    jobs:
      - test_python
